name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    defaults:
      run:
        shell: msys2 {0}
        
    runs-on: windows-latest

    steps:
      - name: 'Setup msys2'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-libpng
            make
            wget
            unzip

      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Fetch Image files'
        working-directory: ./gfx
        run: |
          wget https://brockhaus.org/astonia_client_pngs.zip
          unzip astonia_client_pngs.zip
         
      - name: 'Build Executeable'
        working-directory: ./moac
        run: |
            make

      - name : 'Create ZIP File excluding source code'
        run: |
          zip -r9 moac.zip . -x *.git* -x ./moac/*.c -x ./moac/*.h -x ./moac/*.md -x ./moac/*.rc -x ./moac/*.txt -x ./moac/Makefile

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: astonia-client
          path: ./moac.zip

