name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    defaults:
      run:
        shell: msys2 {0}
        
    runs-on: windows-latest

    steps:
      - name: 'Setup msys2'
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-libpng
            make
            wget
            zip
            unzip
            git
            mingw-w64-x86_64-git-lfs

      - name: 'Install git-lfs'
        run: git-lfs install

      - name: 'Checkout'
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0

      - name: 'Checkout LFS objects'
        run: git lfs checkout


      - name: 'Fetch Image files'
        run: |
          wget https://brockhaus.org/astonia_client_pngs.zip
          unzip astonia_client_pngs.zip
          rm -rf astonia_client_pngs.zip
         
      - name: 'Build Executeable'
        working-directory: ./moac
        run: |
            make

      - name : 'Create ZIP File excluding source code and a bunch of other files'
        run: |
          zip -r9 moac.zip . -x readme.md -x todo.txt -x *.git* -x ./moac/*.c -x ./moac/*.h -x ./moac/*.md -x ./moac/*.rc -x ./moac/*.o -x ./moac/*.txt -x ./moac/Makefile

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.run_id }}
          tag_name: ${{ github.ref }}

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          path: ./moac.zip

